# Generated by Django 4.1.2 on 2022-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
