# Generated by Django 4.1.2 on 2022-10-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signaturedocument_validatedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedocument',
            name='document',
            field=models.FileField(upload_to='validate_document/'),
        ),
    ]
