# Generated by Django 4.1.2 on 2022-10-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_private_key_customuser_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='passphase',
            new_name='passphrase',
        ),
    ]
