# Generated by Django 4.1.2 on 2022-10-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_document_description'),
        ('accounts', '0004_rename_passphase_customuser_passphrase'),
    ]

    operations = [
    ]
