# Generated by Django 4.0.1 on 2022-10-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_document_receiver_alter_document_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='sent_at',
        ),
    ]
